### ISSUE TITLE
Debris Color

### ISSUE THREAD

**Issue by RelatedTitle** [Linko-3D/First-Person-Controller-FPS#1]
Is there a way to make it that the Debris color depends on the color of the thing it hits?

**Comment by Linko-3D** [comment]
Hello, I was thinking about doing that. I don't know if this is possible to get the pixel color.

The method is to create different groups: concrete, wood, rock, etc. You create a different debris colors for each or debris models. Also you can use those same groups for the footstep sounds. You could also use the Enemy group to change the debris color to red.

I think I will add a few groups to generate different debris colors and footstep sound, so you will have a base that you can edit (to match your wood color texture or change the sound when walking on wood for example) and add more easily.

**Comment by Linko-3D** [comment]
Hello, I have updated the script, it will generate debris of the color of the objet it hits. It works with CSG and MeshInstance, the MeshInstance must be the child of the StaticBody, RigidBody or KinematicBody. If no material is applied, it will set the color to white.

You can find the code in Shoot.gd, in the spawn_impact() function.

You must download it from GitHub, I haven't updated it in the AssetLib of Godot.

The yellow particles will be replaced by a smoke effect.
