### ISSUE TITLE
suggestion in move_and_slide

### ISSUE THREAD

**Issue by RichardEllicott** [Linko-3D/First-Person-Controller-FPS#2]
hi again, playing with your controller and i had some rigidbodies found i coud stack them up

i didn't know if you where aware but the infinite_inertia paramaeter in the move_and_slide function set to false allows a player to stack rigid bodies and then walk accross them... it prevents, for the most part,. knocking them aside.... your pickup rigidbodies code then pushes them about it's kinda neat

`
movement = move_and_slide(
            movement,
            Vector3.UP,
            false,
            4,
            0.785398,
            false
            )
`

**Comment by Linko-3D** [comment]
Hello.

Thank you, I have uploaded the new version without infinite inertia.
